# Generated by Django 3.0.7 on 2020-06-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=64, unique=True), max_length=32, unique=True),
        ),
    ]
